# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer',
            field=models.TextField(max_length=300),
        ),
    ]
