# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160530_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='team_member_pics')),
            ],
        ),
    ]
